'''This file contains utility functions that are available to both test cases
and the controller. We name this module in such a way that 3rd-party test cases
can't easily run into the same name.
'''

import os.path
import config

def getLogFolderPath(root, scenarioId):
    '''Return the log folder path given the SyncDET root path and the scenario 
    id'''
    return os.path.join(root, config.LOG_DIR, scenarioId);

def getLogFilePath(pathLogFolder, module, instId, actorId, suffix = ''):
    '''Return the log file path'''
    if suffix is not '': suffix = '-' + suffix;
    name = '{0}-{1}-{2}{3}.log'.format(module, instId, actorId, suffix)
    return os.path.join(pathLogFolder, name)

def getPIDFilePath(pathLogFolder, key, actorId):
    '''Return the PID file path. PID files are generated by 
    syncdet_case_background.startBackgroundProcess()'''
    name = '{0}-{1}.pid'.format(key, actorId)
    return os.path.join(pathLogFolder, name)
